---
resources:
  - name: repo
    type: git
    source:
      uri: https://code.build.djan.org/djanatyn/resume.git
      branch: main

jobs:
  - name: lint-test-build
    plan:
      - get: repo
        trigger: true

      - task: lint-test-build
        config:
          platform: linux

          image_resource:
            type: registry-image
            source:
              repository: registry.build.djan.org/ci/rust
              tag: 1.85.0-bookworm
              username: ((registry.username))
              password: ((registry.password))

          inputs:
            - name: repo

          caches:
            - path: cargo-home/registry
            - path: cargo-home/git
            - path: repo/target

          params:
            CARGO_HOME: cargo-home

          run:
            path: sh
            args:
              - -exc
              - |
                cd repo
                cargo fmt --check
                cargo clippy --locked --all-targets --all-features -- -D warnings
                cargo test --locked
                cargo build --locked
